#!/bin/sh

SPARK_PATH="/home/jia/spark-1.4.0-bin-hadoop2.6/"

#include csv lib
#disable GC limit

$SPARK_PATH/bin/pyspark \
  --master local[2] \
  --packages com.databricks:spark-csv_2.10:1.0.3

#$SPARK_PATH/bin/pyspark \
#  --master local[2] \
#  --conf spark.driver.memory=5g \
#  --conf spark.executor.memory=5g \
#  --conf spark.python.worker.memory=5g \
#  --conf "spark.executor.extraJavaOptions=-XX:-UseGCOverheadLimit" \
#  --packages com.databricks:spark-csv_2.10:1.0.3
