#!/bin/sh

SPARK_PATH="/home/jia/spark-1.4.0-bin-hadoop2.6/"


#$SPARK_PATH/bin/spark-submit $1 \
#  --master local[2] \
#  --packages com.databricks:spark-csv_2.10:1.0.3 \
#  --conf spark.driver.memory=5g \
#  --conf spark.executor.memory=5g \

$SPARK_PATH/bin/spark-submit $1 --master local[2] --packages com.databricks:spark-csv_2.10:1.0.3 \
